language: objective-c
xcode_workspace: Example/PSSRedisClient.xcworkspace
xcode_scheme: PSSRedisClient-Example
xcode_destination: platform=iOS Simulator,OS=11.0,name=iPad Pro (9.7-inch)

script:
- pod lib lint
